[tool.poetry]
name = "gauge-llm"
packages = [
    {include = "gauge"}
]
version = "0.0.121"
description = "Qualitatively evaluate LLMs"
authors = ["Killian Lucas", "Roger Hu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
replicate = "0.8.3"
openai = "^0.27.8"
rich = "^13.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"