[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "archbuilder"
version = "0.1.0"
authors = [
    {name = "Coleman A. Matey", email = "colemanmatey@icloud.com"},
]
description = "A tool to enable developers set up projects quickly"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
archbuilder = "archbuilder.__main__:main"
