[tool.poetry]
name = "PowDeRUL"
version = "1.0.22"
description = "Python package for calculating lifetime of components"
authors = ["Paul Garnier <paul.garnier@ens-rennes.fr>"]

[tool.poetry.dependencies]
python = ">=3.6"
numpy = "^1.24.1"
pandas = "^2.0.1"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
rainflow = "^3.2.0"
openpyxl = "^3.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
