[project]
name = "acapela_downloader_py"
version = "0.0.8"
authors = [
  { name="JWKK"},
]
description = "Acapela pwned but in Python."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://memerdev.com"
"GitHub" = "https://memerdev.com"
