[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thoth_doc"
version = "0.0.9"
authors = [
  { name="Lev", email="smj510black@gmail.com" },
]
description = "Dependency-free, lightweight docstring parser"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Documentation",
]

[project.urls]
"Homepage" = "https://github.com/mariownyou/thoth-doc"
"Bug Tracker" = "https://github.com/mariownyou/thoth-doc/issues"
