[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "federa"
version = "0.0.3"
authors = [
  { name="Anupam Borthakur", email="anupamborthakur@kgpian.iitkgp.ac.in" },
]
description = "FedERA is a highly dynamic and customizable framework that can accommodate many use cases with flexibility by implementing several functionalities over different federated learning algorithms, and essentially creating a plug-and-play architecture to accommodate different use cases."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies = [
  "codecarbon>=2.1.4",
  "grpcio>=1.53.0",
  "numpy>=1.23.4",
  "Pillow>=9.5.0",
  "protobuf>=3.20.2",
  "torch>=2.0.0",
  "torchvision>=0.15.1",
  "tqdm>=4.65.0",
  "bandit"
]

[project.urls]
"Homepage" = "https://github.com/anupamkliv/FedERA"
"Bug Tracker" = "https://github.com/anupamkliv/FedERA/issues"

[tool.hatch.build]
include = [
  "/federa"
]
