- name: set cann tag when scene is a910b
  set_fact:
    cann_tag: ".*6.1.*"
  when: ansible_local.npu_info.scene == 'a910b'

- name: set cann tag when scene is not a910b
  set_fact:
    cann_tag: "((?!6.1).)*"
  when: ansible_local.npu_info.scene != 'a910b'

- name: find kernels script for 310P
  find:
    paths: "{{ cann_dirs }}"
    recurse: no
    file_type: file
    use_regex: yes
    patterns: ".*kernels-310p{{cann_tag}}.sh"
  register: kernels_310P

- name: find kernels run package for 310P
  find:
    paths: "{{ cann_dirs }}"
    recurse: no
    file_type: file
    use_regex: yes
    patterns: ".*kernels-310p{{cann_tag}}.run"
  register: kernels_310P_run

- name: find kernels script for 910
  find:
    paths: "{{ cann_dirs }}"
    recurse: no
    file_type: file
    use_regex: yes
    patterns: ".*kernels-910{{cann_tag}}.sh"
  register: kernels_910

- name: find kernels run package for 910
  find:
    paths: "{{ cann_dirs }}"
    recurse: no
    file_type: file
    use_regex: yes
    patterns: ".*kernels-910{{cann_tag}}.run"
  register: kernels_910_run

- name: set log_path for root
  set_fact:
    log_path: /var/log/ascend_seclog/
  when: ansible_user_uid == 0 and (kernels_310P.matched > 0 or kernels_910.matched > 0)

- name: set log_path for non-root
  set_fact:
    log_path: ~/var/log/ascend_seclog/
  when: ansible_user_uid != 0 and (kernels_310P.matched > 0 or kernels_910.matched > 0)

- name: get kernels version
  shell: echo $(basename {{kernels_910_run.files[0].path}}) | awk -F '_' '{print $2}'
  register: kernels_ver
  when: kernels_910_run.matched > 0

- name: set kernels_version fact
  set_fact:
    kernels_version: "{{kernels_ver.stdout}}"
    cacheable: yes
  when: kernels_910_run.matched > 0

- name: get kernels version again
  shell: echo $(basename {{kernels_310P_run.files[0].path}}) | awk -F '_' '{print $2}'
  register: kernels_ver
  when: kernels_910_run.matched == 0 and kernels_310P_run.matched > 0

- name: set kernels_version fact again
  set_fact:
    kernels_version: "{{kernels_ver.stdout}}"
    cacheable: yes
  when: kernels_910_run.matched == 0 and kernels_310P_run.matched > 0

- name: set kernels_version when can not find kernels
  set_fact:
    kernels_version: "NA"
    cacheable: yes
  when: kernels_910_run.matched == 0 and kernels_310P_run.matched == 0

- name: check if toolkit is installed
  find:
    paths: "{{ascend_install_path}}/ascend-toolkit/{{kernels_version}}"
    recurse: yes
    file_type: file
    use_regex: yes
    patterns: "ascend_toolkit_install.info"
  register: toolkit_status
  when: kernels_version != 'NA'

- name: check if nnae is installed
  find:
    paths: "{{ascend_install_path}}/nnae/{{kernels_version}}"
    recurse: no
    file_type: file
    use_regex: yes
    patterns: "ascend_nnae_install.info"
  register: nnae_status
  when: kernels_version != 'NA' and toolkit_status.matched == 0

- name: message
  debug:
    msg:
      - "The nnae and toolkit packages are not installed, kernels install skipped"
  when: kernels_version != 'NA' and toolkit_status.matched == 0 and nnae_status.matched == 0

- name: set kernels_type
  set_fact:
    kernels_type: "{{'toolkit' if toolkit_status.matched > 0 else 'nnae'}}"
  when: kernels_version != 'NA'

- name: install kernels using scripts for 310P
  shell: "bash {{ kernels_310P.files[0].path }} {{ log_path }} {{ kernels_type }}"
  environment:
    PATH: "{{ local_path }}/{{ python_version }}/bin:{{ansible_env.PATH}}"
    LD_LIBRARY_PATH: "{{ local_path }}/{{ python_version }}/lib"
  register: kernels_310P_result
  when:
    - kernels_310P.matched > 0
    - toolkit_status.matched > 0 or nnae_status.matched > 0
  failed_when: kernels_310P_result.rc != 0

- name: message for 310P
  debug:
    msg:
      - "{{ kernels_310P_result | default('NOT DEFINED') }}"
  when: kernels_310P_result.changed

- name: install kernels for 310P
  shell: "bash {{ kernels_310P_run.files[0].path }} --install --type={{ kernels_type }}"
  environment:
    PATH: "{{ local_path }}/{{ python_version }}/bin:{{ansible_env.PATH}}"
    LD_LIBRARY_PATH: "{{ local_path }}/{{ python_version }}/lib"
  register: kernels_310P_run_result
  when:
    - kernels_310P_run.matched > 0 and kernels_310P.matched == 0
    - toolkit_status.matched > 0 or nnae_status.matched > 0
  failed_when: kernels_310P_run_result.rc != 0

- name: message for 310P
  debug:
    msg:
      - "{{ kernels_310P_run_result | default('NOT DEFINED') }}"
  when: kernels_310P_run_result.changed

- name: message for 310P
  debug:
    msg:
      - "can not find kernels package for 310P, kernels install skipped"
  when: kernels_310P_run.matched == 0

- name: install kernels using scripts for 910
  shell: "bash {{ kernels_910.files[0].path }} {{ log_path }} {{ kernels_type }}"
  environment:
    PATH: "{{ local_path }}/{{ python_version }}/bin:{{ansible_env.PATH}}"
    LD_LIBRARY_PATH: "{{ local_path }}/{{ python_version }}/lib"
  register: kernels_910_result
  when:
    - kernels_910.matched > 0
    - toolkit_status.matched > 0 or nnae_status.matched > 0
  failed_when: kernels_910_result.rc != 0

- name: message for 910
  debug:
    msg:
      - "{{ kernels_910_result | default('NOT DEFINED') }}"
  when: kernels_910_result.changed

- name: install kernels for 910
  shell: "bash {{ kernels_910_run.files[0].path }} --install --type={{ kernels_type }}"
  environment:
    PATH: "{{ local_path }}/{{ python_version }}/bin:{{ansible_env.PATH}}"
    LD_LIBRARY_PATH: "{{ local_path }}/{{ python_version }}/lib"
  register: kernels_910_run_result
  when:
    - kernels_910_run.matched > 0 and kernels_910.matched == 0
    - toolkit_status.matched > 0 or nnae_status.matched > 0
  failed_when: kernels_910_run_result.rc != 0

- name: message for 910
  debug:
    msg:
      - "{{ kernels_910_run_result | default('NOT DEFINED') }}"
  when: kernels_910_run_result.changed

- name: message for 910
  debug:
    msg:
      - "can not find kernels package for 910, kernels install skipped"
  when: kernels_910_run.matched == 0