[tool.poetry]
name = "contact-magic"
version = "0.1.0"
description = "Quickly set up workflows for retrieving hard-to-find contact information and composing personalized messages based on any data point."
authors = ["Copyfactory <dev@copyfactory.io>"]
readme = "README.md"
license = "MIT"
packages = [{include = "contact_magic"}]
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.9.0"}
httpx = "^0.24.1"
pandas = "^2.0.2"
gspread = "4.0.1"
oauth2client = "4.1.3"
oauthlib = "3.1.1"
python-dotenv = "^1.0.0"
pydantic = "1.10.8"
structlog = "23.1.0"
rich = "^13.4.1"

[tool.flit.metadata.requires-extra]
dev = [
    "pre-commit >=2.17.0,<3.0.0",
]

[tool.poetry.scripts]
contact-magic = "scripts.agency:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
