[tool.poetry]
name = "django-join-unrelated"
version = "0.1.0"
description = "Join Django ORM models having no relations."
authors = ["Denis Kazakov <denis@kazakov.ru.net>"]
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/django-join-unrelated"
repository = "https://github.com/KazakovDenis/django-join-unrelated"
keywords = ["django", "django-orm", "orm"]
classifiers = [
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
Django = "^3.2"
django-stubs = "^4"
coverage = {extras = ["toml"], version = "^7"}
flake8 = "^5"
flake8-annotations-complexity = "^0"
flake8-broken-line = "^1"
flake8-builtins = "^2"
flake8-cognitive-complexity = "^0"
flake8-commas = "^2"
flake8-comprehensions = "^3"
flake8-eradicate = "^1"
flake8-expression-complexity = "^0"
flake8-fixme = "^1"
flake8-print = "^5"
flake8-pytest = "^1"
flake8-pytest-style = "^1"
flake8-quotes = "^3"
flake8-return = "^1"
flake8_simplify = "^0"
flake8-typing-imports = "^1"
flake8-variables-names = "^0"
isort = "^5"
mypy = "^1"
psycopg2-binary = "<=3"
pyproject-flake8 = "^5"
pytest = "^7"
pytest-django = "^4"

[build-system]
requires = ["poetry-core<1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
command_line = "-m pytest"
source = ["django_join_unrelated"]
omit = ["*/tests/*"]

[tool.coverage.report]
fail_under = 0
show_missing = true
sort = "Stmts"
omit = ["*/tests/*"]

[tool.flake8]
min-python-version = 3.8
max-line-length = 120
max-complexity = 10
exclude = [
    ".git",
    ".idea",
    ".pytest_cache",
    ".mypy_cache",
    "__pycache__"
]
max-cognitive-complexity = 10
per-file-ignores = [
    "django_join_unrelated/__init__.py:F401"
]
pytest-fixture-no-parentheses = true
pytest-parametrize-names-type = "csv"

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
lines_between_sections = 1
line_length = 120
use_parentheses = true
include_trailing_comma = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["django_join_unrelated", "app", "tests"]

[tool.mypy]
python_version = "3.8"
warn_unused_configs = true
files = ["django_join_unrelated"]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "app.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings"
