[tool.poetry]
name = "lazy-calculator"
version = "0.1.4"
description = "A Powerful Python Library for Effortless Calculations"
authors = ["ppirch"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "lazy_calculator"}]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"