[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pnsgraph"
version = "0.0.3"
authors = [
    { name="John Frederick Tapia", email="john.frederick.tapia@dlsu.edu.ph"},
]
description = "Python Implementation of P-graph Algorithms for Process Network Synthesis"
readme = "README.md"
install_requires = ['pulp', 'itertools']
requires-python = ">=3.7"
license = {file="LICENSE"}
keywords = ['p-graph', 'network', 'process synthesis']
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ['pulp', 'itertools']

[project.urls]
"Homepage" = "https://github.com/fredtapia/PNS-Graph"