[tool.poetry]
name = "newrelic-sb-sdk"
version = "0.6.0"
description = "New Relic SDK to interact with Nerdgraph API."
authors = [
  "SoftButterfly Development Team <dev@softbutterfly.io>",
  "zodiacfireworks <martin.vuelta@gmail.com>"
]
license = "MIT License"
readme = "README.md"
homepage = "https://gitlab.com/softbutterfly/open-source/newrelic-sb-sdk"
repository = "https://gitlab.com/softbutterfly/open-source/newrelic-sb-sdk"
documentation = "https://gitlab.com/softbutterfly/open-source/newrelic-sb-sdk/-/wikis"
keywords = [
  "Softbutterfly",
  "New Relic",
  "SDK",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "newrelic_sb_sdk", from = "src" },
]
include = [
  "LICENSE.txt",
  "CHANGELOG.md",
]

[tool.poetry.urls]
"Download" = "https://gitlab.com/softbutterfly/open-source/newrelic-sb-sdk/-/archive/v0.6.0/newrelic-sb-sdk-v0.6.0.tar.gz"
"Bug Tracker" = "https://gitlab.com/softbutterfly/open-source/newrelic-sb-sdk/-/issues"


[tool.poetry.dependencies]
python = ">=3.8.1,<4.0.0"
enforce-typing = "^1.0.0.post1"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
semver = "^3.0.0"
sgqlc = "^16.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
bandit = "^1.7.5"
black = "^23.3.0"
coverage = "^7.2.7"
flake8 = "^6.0.0"
flake8-black = "^0.3.6"
importnb = "^2023.1.7"
ipympl = "^0.9.3"
isort = "^5.12.0"
jupyter-book = "^0.15.1"
jupyterlab = "^4.0.1"
matplotlib = "^3.7.1"
mypy = "^1.3.0"
nbdev = "^2.3.12"
nbmake = "^1.4.1"
nbqa = {extras = ["toolchain"], version = "^1.7.0"}
numpy = "^1.24.3"
pandas = "^2.0.2"
pre-commit = "^3.3.2"
pycodestyle = "^2.10.0"
pydocstyle = "^6.3.0"
pylint = "^2.17.4"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
pytest-vcr = "^1.0.2"
pytest-xdist = "^3.3.1"
tbump = "^6.10.0"
tox = "^4.5.2"
types-requests = "^2.31.0.1"

[tool.black]
target_version = ['py311']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.eggs
  |\.hg
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
  |legacy
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
