[tool]
[tool.poetry]
name = "jwtlib"
version = "0.3.3"
description = "A little helper library to streamline working with JWT in python"
readme = "README.rst"
repository = "http://github.com/novopl/jwtlib"
homepage = "http://novopl.github.com/jwtlib"
documentation = "http://novopl.github.com/jwtlib"
authors = ["Mateusz Klos <novopl@gmail.com>"]
license = "Apache 2.0"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
packages = [
    { include = "jwtlib", from = "src" },
]
include = ["LICENSE", "AUTHORS", "README.rst"]
exclude = ["docs/**"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
pyjwt = ">=2.4.0"

[tool.poetry.dev-dependencies]
coverage = "^7.2.7"
factory-boy = "^3.2.1"
flake8 = "^6.0.0"
more-itertools = "^9.1.0"
mypy = "^1.3.0"
peltak = "^0.30.0"
pycodestyle = "^2.10.0"
pylint = "^2.17.4"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
pytest-sugar = "^0.9.7"
requests = "^2.25.1"
Sphinx = ">6.0,<7.0"
sphinx-refdoc = "^0.3.0"
sphinx_rtd_theme = "^1.2.2"
sphinxcontrib-plantuml = "^0.25"
peltak-todos = "^0.0.10"
peltak-changelog = "^0.0.4"
peltak-gitflow = "^0.0.4"


[tool.pytest.ini_options]
addopts = "--durations=3"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ELLIPSIS"


[tool.coverage.run]
branch = true
source = ['src']
omit = []

[tool.coverage.report]
exclude_lines = ['nocov']




[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


##################
#     PYTEST     #
##################

